
repo = "~/0Git/dotfiles-promax/configma"

profiles = [
  {
    name = "gl553ve",
    modules = [
      "nixos",
      "env",
      "tools",
      "kde-gl553ve",
      "games-gl553ve",
    ],
  },
  {
    name = "ga402xu",
    modules = [
      "nixos",
      "env",
      "tools",
      "kde-ga402xu",
      "games-ga402xu",
    ],
  },
  {
    name = "nothing",
    modules = [
      "tools",
      "env",
      "phone",
      "phone-private",
    ],
  },
]

modules = [
  { name = "phone-private", path = "~/0Git/dotfiles-promax-private/configma" },
  # { name = "game-savefiles", path = "~/0Git/game-savefiles" },
]
