
notARepository: quit

git:
  paging:
    # externalDiffCommand: difft --color=always
    externalDiffCommand: delta --color-only
    pager: delta --paging=never

# OOF: lazygit keybinding configuration sucks
# keybinding:
#   universal:
#     pullFiles: f
#     pushFiles: p
#     prevBlock-alt: H
#     nextBlock-alt: L
#     nextBlock-alt2: <tab>
#     prevBlock-alt2: <backtab>
#     goInto: l
#     return: <esc>
#     return: h
#     # scrollUpMain-alt1: <c-k>
#     # scrollDownMain-alt1: <c-j>
#     # rangeSelectDown: J
#     # rangeSelectUp: K

#     # oof. does not work
#     # scrollLeft: <c-h>
#     # scrollRight: <c-l>

