# alacritty.toml

live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 12
y = 12

[scrolling]
history = 12000