

# - [Home · hyprland-community/pyprland Wiki · GitHub](https://github.com/hyprland-community/pyprland/wiki)

[pyprland]
plugins = [
  "toggle_special",
  "layout_center",
]

[layout_center]
margin = 0
offset = [0, 40]
captive_focus = false
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"


